import "./globals.css";

import { Inter } from "next/font/google";
import { ProgramOutputProvider } from '@/contexts/ProgramOutputContext';
import { ViewManagerProvider } from '@/contexts/ViewManagerContext';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin></link>
        <link href="https://fonts.googleapis.com/css2?family=Space+Mono:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet"></link>
      </head>
      <ProgramOutputProvider>
        <ViewManagerProvider>
          <body className={inter.className}>{children}</body>
        </ViewManagerProvider>
      </ProgramOutputProvider>
    </html>
  );
}
