// Created by Brayan Vizcaino on 4/3/24.


#ifndef ABSTRACTSYNTAXTREE_ABSTRACTSYNTAXTREE_HPP
#define ABSTRACTSYNTAXTREE_ABSTRACTSYNTAXTREE_HPP


class AbstractSyntaxTree {

};


#endif //ABSTRACTSYNTAXTREE_ABSTRACTSYNTAXTREE_HPP